/* C0 control codes */
#define NUL "\0"
#define SOH "\x01"
#define STX "\x02"
#define ETX "\x03"
#define EOT "\x04"
#define ENQ "\x05"
#define ACK "\x06"
#define BEL "\a"
#define BS "\b"
#define HT "\t"
#define LF "\n"
#define VT "\v"
#define FF "\f"
#define CR "\r"
#define SO "\x0E"
#define SI "\x0F"
#define DLE "\x10"
#define DC1 "\x11"
#define DC2 "\x12"
#define DC3 "\x13"
#define DC4 "\x14"
#define NAK "\x15"
#define SYN "\x16"
#define ETB "\x17"
#define CAN "\x18"
#define EM "\x19"
#define SUB "\x1A"
#define ESC "\x1B"
#define FS "\x1C"
#define GS "\x1D"
#define RS "\x1E"
#define US "\x1F"

#define DEL "\x7F"

/* C1 control codes */
#define CSI ESC "["
#define SS2 ESC "N"
#define SS3 ESC "O"
#define DCS ESC "P"
#define ST ESC "\\"
#define OSC ESC "]"
#define SOS ESC "X"
#define PM ESC "^"
#define APC ESC "_"
